name: rick_and_morty_prj
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  vexana: ^5.0.3
  intl_utils: ^2.8.10
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/locales/en.json
    - assets/locales/tr.json

